name: build-remindif-apk

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
#      - run: flutter packages pub run build_runner build # adding these as pre generated
      - run: flutter pub run flutter_launcher_icons
      - name: Make .env file
          uses: SpicyPizza/create-envfile@v2.0
          with:
            envkey_google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      # - run: flutter test
      - run: flutter build apk
      - name: Upload apk
          # uses: actions/upload-artifact@v2
          # with:
        # path: "build/app/outputs/flutter-apk/app-release.apk"
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ github.run_id }}"
          body: "commit: ${{ github.sha }}, build run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
